@Echo Off
mode con: cols=50 lines=15
Title Created By Shimul Tech Tips Team & Color 30
echo Do Not Close This Window....
echo ............................

%~d0
CD %~dp0

echo Installing IDM...
TASKKILL /F /IM IDMan.exe
TASKKILL /F /IM IEMonitor.exe
"Internet Download Manager(IDM) - shimultechtips.exe" /skipdlgs

echo ...................................
echo Run IDM From The Desktop Shortcut..
echo ...................................
echo Wait Untill You Get IDM GUI........
echo ...................................
pause

echo Activating IDM...
start "" "Internet Download Manager(IDM) Activator - shimultechtips.exe"